package com.github.kklisura.cdt.protocol.types.preload;

import com.fasterxml.jackson.annotation.JsonProperty;

/** List of FinalStatus reasons for Prerender2. */
public enum PrerenderFinalStatus {
  @JsonProperty("Activated")
  ACTIVATED,
  @JsonProperty("Destroyed")
  DESTROYED,
  @JsonProperty("LowEndDevice")
  LOW_END_DEVICE,
  @JsonProperty("InvalidSchemeRedirect")
  INVALID_SCHEME_REDIRECT,
  @JsonProperty("InvalidSchemeNavigation")
  INVALID_SCHEME_NAVIGATION,
  @JsonProperty("InProgressNavigation")
  IN_PROGRESS_NAVIGATION,
  @JsonProperty("NavigationRequestBlockedByCsp")
  NAVIGATION_REQUEST_BLOCKED_BY_CSP,
  @JsonProperty("MainFrameNavigation")
  MAIN_FRAME_NAVIGATION,
  @JsonProperty("MojoBinderPolicy")
  MOJO_BINDER_POLICY,
  @JsonProperty("RendererProcessCrashed")
  RENDERER_PROCESS_CRASHED,
  @JsonProperty("RendererProcessKilled")
  RENDERER_PROCESS_KILLED,
  @JsonProperty("Download")
  DOWNLOAD,
  @JsonProperty("TriggerDestroyed")
  TRIGGER_DESTROYED,
  @JsonProperty("NavigationNotCommitted")
  NAVIGATION_NOT_COMMITTED,
  @JsonProperty("NavigationBadHttpStatus")
  NAVIGATION_BAD_HTTP_STATUS,
  @JsonProperty("ClientCertRequested")
  CLIENT_CERT_REQUESTED,
  @JsonProperty("NavigationRequestNetworkError")
  NAVIGATION_REQUEST_NETWORK_ERROR,
  @JsonProperty("MaxNumOfRunningPrerendersExceeded")
  MAX_NUM_OF_RUNNING_PRERENDERS_EXCEEDED,
  @JsonProperty("CancelAllHostsForTesting")
  CANCEL_ALL_HOSTS_FOR_TESTING,
  @JsonProperty("DidFailLoad")
  DID_FAIL_LOAD,
  @JsonProperty("Stop")
  STOP,
  @JsonProperty("SslCertificateError")
  SSL_CERTIFICATE_ERROR,
  @JsonProperty("LoginAuthRequested")
  LOGIN_AUTH_REQUESTED,
  @JsonProperty("UaChangeRequiresReload")
  UA_CHANGE_REQUIRES_RELOAD,
  @JsonProperty("BlockedByClient")
  BLOCKED_BY_CLIENT,
  @JsonProperty("AudioOutputDeviceRequested")
  AUDIO_OUTPUT_DEVICE_REQUESTED,
  @JsonProperty("MixedContent")
  MIXED_CONTENT,
  @JsonProperty("TriggerBackgrounded")
  TRIGGER_BACKGROUNDED,
  @JsonProperty("EmbedderTriggeredAndCrossOriginRedirected")
  EMBEDDER_TRIGGERED_AND_CROSS_ORIGIN_REDIRECTED,
  @JsonProperty("MemoryLimitExceeded")
  MEMORY_LIMIT_EXCEEDED,
  @JsonProperty("FailToGetMemoryUsage")
  FAIL_TO_GET_MEMORY_USAGE,
  @JsonProperty("DataSaverEnabled")
  DATA_SAVER_ENABLED,
  @JsonProperty("HasEffectiveUrl")
  HAS_EFFECTIVE_URL,
  @JsonProperty("ActivatedBeforeStarted")
  ACTIVATED_BEFORE_STARTED,
  @JsonProperty("InactivePageRestriction")
  INACTIVE_PAGE_RESTRICTION,
  @JsonProperty("StartFailed")
  START_FAILED,
  @JsonProperty("TimeoutBackgrounded")
  TIMEOUT_BACKGROUNDED,
  @JsonProperty("CrossSiteRedirect")
  CROSS_SITE_REDIRECT,
  @JsonProperty("CrossSiteNavigation")
  CROSS_SITE_NAVIGATION,
  @JsonProperty("SameSiteCrossOriginRedirect")
  SAME_SITE_CROSS_ORIGIN_REDIRECT,
  @JsonProperty("SameSiteCrossOriginRedirectNotOptIn")
  SAME_SITE_CROSS_ORIGIN_REDIRECT_NOT_OPT_IN,
  @JsonProperty("SameSiteCrossOriginNavigationNotOptIn")
  SAME_SITE_CROSS_ORIGIN_NAVIGATION_NOT_OPT_IN,
  @JsonProperty("ActivationNavigationParameterMismatch")
  ACTIVATION_NAVIGATION_PARAMETER_MISMATCH,
  @JsonProperty("ActivatedInBackground")
  ACTIVATED_IN_BACKGROUND,
  @JsonProperty("EmbedderHostDisallowed")
  EMBEDDER_HOST_DISALLOWED,
  @JsonProperty("ActivationNavigationDestroyedBeforeSuccess")
  ACTIVATION_NAVIGATION_DESTROYED_BEFORE_SUCCESS,
  @JsonProperty("TabClosedByUserGesture")
  TAB_CLOSED_BY_USER_GESTURE,
  @JsonProperty("TabClosedWithoutUserGesture")
  TAB_CLOSED_WITHOUT_USER_GESTURE,
  @JsonProperty("PrimaryMainFrameRendererProcessCrashed")
  PRIMARY_MAIN_FRAME_RENDERER_PROCESS_CRASHED,
  @JsonProperty("PrimaryMainFrameRendererProcessKilled")
  PRIMARY_MAIN_FRAME_RENDERER_PROCESS_KILLED,
  @JsonProperty("ActivationFramePolicyNotCompatible")
  ACTIVATION_FRAME_POLICY_NOT_COMPATIBLE,
  @JsonProperty("PreloadingDisabled")
  PRELOADING_DISABLED,
  @JsonProperty("BatterySaverEnabled")
  BATTERY_SAVER_ENABLED,
  @JsonProperty("ActivatedDuringMainFrameNavigation")
  ACTIVATED_DURING_MAIN_FRAME_NAVIGATION,
  @JsonProperty("PreloadingUnsupportedByWebContents")
  PRELOADING_UNSUPPORTED_BY_WEB_CONTENTS
}
